# Generated by Django 3.1.1 on 2020-11-17 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20201117_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('cardNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('cardFirstName', models.CharField(max_length=100, null=True)),
                ('cardLastName', models.CharField(max_length=100, null=True)),
                ('securityCode', models.IntegerField()),
                ('expirationDate', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
