# Generated by Django 3.1.2 on 2020-10-20 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksiteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorId', models.IntegerField(primary_key=True, serialize=False)),
                ('authorName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('userName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authorName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisherId', models.IntegerField(primary_key=True, serialize=False)),
                ('publisherName', models.CharField(max_length=100, null=True)),
                ('authors', models.ManyToManyField(to='booksiteapp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.IntegerField(primary_key=True, serialize=False)),
                ('commentContent', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksiteapp.book')),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksiteapp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('adressId', models.IntegerField(primary_key=True, serialize=False)),
                ('streetName', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('zip', models.IntegerField()),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksiteapp.siteuser')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='booksiteapp.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='booksiteapp.Publisher'),
        ),
    ]
