# Generated by Django 3.1.2 on 2020-10-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksiteapp', '0002_auto_20201020_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('subtotal', models.IntegerField()),
                ('siteUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booksiteapp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderId',
            fields=[
                ('OrderId', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksiteapp.book')),
                ('ShoppingCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksiteapp.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('cardNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('cardFirstName', models.CharField(max_length=100, null=True)),
                ('cardLastName', models.CharField(max_length=100, null=True)),
                ('securityCode', models.IntegerField()),
                ('expirationDate', models.IntegerField()),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksiteapp.siteuser')),
            ],
        ),
    ]
